export interface QuestionBank {
	es: string[];
	en: string[];
}

export const QUESTIONS: QuestionBank = {
	es: [
		'¿Quién es más probable que llegue tarde a su propia boda?',
		'¿Quién es más probable que sobreviva a un apocalipsis zombie?',
		'¿Quién es más probable que se haga famoso en TikTok?',
		'¿Quién es más probable que llore viendo una película romántica?',
		'¿Quién es más probable que gaste todo su sueldo en un día?',
		'¿Quién es más probable que se pierda en su propia ciudad?',
		'¿Quién es más probable que hable dormido?',
		'¿Quién es más probable que se convierta en millonario?',
		'¿Quién es más probable que participe en un reality show?',
		'¿Quién es más probable que termine en la cárcel por algo tonto?',
		'¿Quién es más probable que se coma la última rebanada de pizza sin preguntar?',
		'¿Quién es más probable que olvide el cumpleaños de su mejor amigo?',
		'¿Quién es más probable que se duerma en una fiesta?',
		'¿Quién es más probable que mande un mensaje vergonzoso a la persona equivocada?',
		'¿Quién es más probable que conquiste el mundo?',
		'¿Quién es más probable que viva en otro país?',
		'¿Quién es más probable que escriba un libro?',
		'¿Quién es más probable que se tatúe algo de lo que se arrepiente?',
		'¿Quién es más probable que adopte 10 gatos?',
		'¿Quién es más probable que se quede sin batería en el peor momento?',
		'¿Quién es más probable que diga una mentira obvia?',
		'¿Quién es más probable que se caiga en público?',
		'¿Quién es más probable que se disfrace de algo ridículo?',
		'¿Quién es más probable que stalkee a su ex en redes?',
		'¿Quién es más probable que sea el último en enterarse de un chisme?',
		'¿Quién es más probable que gane un concurso de comer?',
		'¿Quién es más probable que sobreviva solo en una isla desierta?',
		'¿Quién es más probable que diga lo que piensa sin filtro?',
		'¿Quién es más probable que se enamore a primera vista?',
		'¿Quién es más probable que pierda su celular cada semana?',
		'¿Quién es más probable que se ría en un momento inapropiado?',
		'¿Quién es más probable que se vuelva vegetariano?',
		'¿Quién es más probable que haga un escándalo en un restaurante?',
		'¿Quién es más probable que invente una excusa para no ir a trabajar?',
		'¿Quién es más probable que llame a su madre para todo?',
		'¿Quién es más probable que sea el alma de la fiesta?',
		'¿Quién es más probable que llore en público?',
		'¿Quién es más probable que tenga un canal de YouTube?',
		'¿Quién es más probable que se mude al campo?',
		'¿Quién es más probable que pelee con un extraño por una tontería?',
		'¿Quién es más probable que haga trampa en un juego de mesa?',
		'¿Quién es más probable que cante en la ducha a todo volumen?',
		'¿Quién es más probable que se quede hablando con un desconocido?',
		'¿Quién es más probable que se olvide dónde estacionó el carro?',
		'¿Quién es más probable que lea los términos y condiciones?',
		'¿Quién es más probable que se haga viral por algo vergonzoso?',
		'¿Quién es más probable que sea presidente?',
		'¿Quién es más probable que se case primero?',
		'¿Quién es más probable que tropiece subiendo escaleras?',
		'¿Quién es más probable que diga "sí" a todo?',
	],
	en: [
		'Who is most likely to be late to their own wedding?',
		'Who is most likely to survive a zombie apocalypse?',
		'Who is most likely to go viral on TikTok?',
		'Who is most likely to cry watching a romantic movie?',
		'Who is most likely to spend their entire paycheck in a day?',
		'Who is most likely to get lost in their own city?',
		'Who is most likely to talk in their sleep?',
		'Who is most likely to become a millionaire?',
		'Who is most likely to be on a reality show?',
		'Who is most likely to end up in jail for something silly?',
		'Who is most likely to eat the last slice of pizza without asking?',
		'Who is most likely to forget their best friend\'s birthday?',
		'Who is most likely to fall asleep at a party?',
		'Who is most likely to send an embarrassing text to the wrong person?',
		'Who is most likely to take over the world?',
		'Who is most likely to live in another country?',
		'Who is most likely to write a book?',
		'Who is most likely to get a tattoo they regret?',
		'Who is most likely to adopt 10 cats?',
		'Who is most likely to run out of battery at the worst time?',
		'Who is most likely to tell an obvious lie?',
		'Who is most likely to trip in public?',
		'Who is most likely to wear a ridiculous costume?',
		'Who is most likely to stalk their ex on social media?',
		'Who is most likely to be the last one to hear gossip?',
		'Who is most likely to win an eating contest?',
		'Who is most likely to survive alone on a deserted island?',
		'Who is most likely to speak without a filter?',
		'Who is most likely to fall in love at first sight?',
		'Who is most likely to lose their phone every week?',
		'Who is most likely to laugh at an inappropriate moment?',
		'Who is most likely to go vegetarian?',
		'Who is most likely to make a scene at a restaurant?',
		'Who is most likely to make up an excuse to skip work?',
		'Who is most likely to call their mom for everything?',
		'Who is most likely to be the life of the party?',
		'Who is most likely to cry in public?',
		'Who is most likely to start a YouTube channel?',
		'Who is most likely to move to the countryside?',
		'Who is most likely to argue with a stranger over nothing?',
		'Who is most likely to cheat at a board game?',
		'Who is most likely to sing in the shower at full volume?',
		'Who is most likely to start talking to a random stranger?',
		'Who is most likely to forget where they parked?',
		'Who is most likely to actually read the terms and conditions?',
		'Who is most likely to go viral for something embarrassing?',
		'Who is most likely to become president?',
		'Who is most likely to get married first?',
		'Who is most likely to trip going up stairs?',
		'Who is most likely to say yes to everything?',
	],
};

export function getRandomQuestion(locale: string, usedIndices: Set<number>): { question: string; index: number } | null {
	const bank = locale === 'en' ? QUESTIONS.en : QUESTIONS.es;
	const available = bank.map((q, i) => i).filter((i) => !usedIndices.has(i));
	if (available.length === 0) return null;
	const idx = available[Math.floor(Math.random() * available.length)];
	return { question: bank[idx], index: idx };
}
